### ISSUE TITLE
跑不起来啊兄弟

### ISSUE THREAD

**Issue by xwlcn** [junicorn/java-china#48]
首先，eclipse导入发现是个java工程，无法tomcat启动，后面才发现Blade这个框架，于是找到了它的官网，知道端口是9000，启动Application后就报错：
com.blade.exception.BladeException: java.lang.NullPointerException
	at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:71)
	at com.blade.mvc.DispatcherHandler.routeHandle(DispatcherHandler.java:192)
	at com.blade.mvc.DispatcherHandler.handle(DispatcherHandler.java:102)
	at com.blade.mvc.DispatcherServlet.service(DispatcherServlet.java:56)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.javachina.controller.IndexController.putData(IndexController.java:166)
	at com.javachina.controller.IndexController.show_home(IndexController.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.blade.kit.reflect.ReflectKit.invokeMehod(ReflectKit.java:313)
	at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:50)
	... 23 more

还有就是在oschina上看到的配置说明根本对不上，没找到blade.properties这个配置文件，希望能用点心出个详细的部署文档，毕竟这也是自己花了时间和心血去写的。让别人下载下来导入maven工程下载依赖jar包也是要时间的，最后却发现跑不起来，让人感到很郁闷啊。

**Comment by xwlcn** [comment]
上个issue就是解决办法。。跑起来了。不过mvn install是个jar文件怎么放tomcat里跑？

**Comment by biezhi** [comment]
blade相关的项目都不用放在tomcat里的，这里的文档我会再写详细一些，最近也会修复一些bug，感谢你的支持，有疑问可以加Blade群：1013565
