### ISSUE TITLE
您好，对于javachina项目有一些问题想请教！

### ISSUE THREAD

**Issue by quasimodoo** [junicorn/java-china#56]
在blade.properties中的配置邮箱
app.mail.host = smtp.qq.com
app.mail.nick = Java\u4E2D\u56FD
app.mail.user = support@java-china.org
app.mail.pass = ***************
app.mail.admin = support@java-china.org
可以讲一下每一个具体填什么吗？我试了半天没有效果，谢谢啦

**Comment by biezhi** [comment]
这个要看你使用的邮件服务器了和协议

**Comment by quasimodoo** [comment]
app.mail.host = smtp.qq.com                 
app.mail.nick = Java\u4E2D\u56FD
app.mail.user = support@java-china.org    邮箱地址
app.mail.pass = ***************          邮箱密码
app.mail.admin = support@java-china.org  邮箱地址

我用QQ邮箱的话第一个不改，第三四五行这样改对吗，第二个不知怎么改

**Comment by biezhi** [comment]
`app.mail.user` 是你的发件邮箱地址
`app.mail.admin` 同样

**Comment by quasimodoo** [comment]
个人QQ邮箱可以用吗？还有第二行的nick该怎么改啊大大~~~

**Comment by biezhi** [comment]
个人的我没试过，我之前用的腾讯的域名邮箱，nick就是发件人的称呼 `unicode` 编码

**Comment by quasimodoo** [comment]
好的，我去注册一个域名邮箱~~~

**Comment by quasimodoo** [comment]
那个，发帖发中文就会变成一堆问号，还有管理员不能删除帖子~~~需要修改程序吗

**Comment by biezhi** [comment]
@quasimodoo 可以具体说一下原因，管理员不能删帖属于 `bug` ，发帖中文乱码得确认一下你的mysql数据库编码

**Comment by quasimodoo** [comment]
哈哈，邮箱通知被标记为垃圾邮件了，刚才看到，已经解决了，谢谢

**Comment by quasimodoo** [comment]
重新去github下了您的项目，申请好了域名邮箱，是QQ的，如下填写后不能正常发送激活邮件，请问怎么解决吖~~~
# email init
mail.smtp.host=smtp.qq.com
mail.user=quasimodo@xuxuran.cn
mail.pass=域名邮箱密码
mail.from=发件人的unicode编码

**Comment by biezhi** [comment]
是怎么个 `不能正常发送激活邮件`

**Comment by quasimodoo** [comment]
填写完点击注册后提示“已向xxx邮箱发送注册链接”，登录邮箱之后没有收到邮件

**Comment by biezhi** [comment]
系统没有错误日志什么的吗？是不是后台报错了

**Comment by quasimodoo** [comment]
对的，报错了
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.qq.com:25
Caused by: javax.mail.AuthenticationFailedException: 530 Error: A secure connection is requiered(such as ssl). More information at http://service.mail.qq.com/cgi-bin/help?id=28

**Comment by biezhi** [comment]
http://blog.csdn.net/ontheway20/article/details/17964593

**Comment by quasimodoo** [comment]
原来是我开启了邮箱保护服务，无法使用IMAP/SMTP服务~~~哈哈，我去关了试试

**Comment by quasimodoo** [comment]
开启了smtp服务还是会报错
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.qq.com:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at com.javachina.kit.MailKit.lambda$0(MailKit.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.AuthenticationFailedException: 530 Error: A secure connection is requiered(such as ssl). More information at http://service.mail.qq.com/cgi-bin/help?id=28

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:892)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:814)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:728)
	at javax.mail.Service.connect(Service.java:386)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 5 more
